= Mesures i aplicació a la contractació
:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]

== Mesures d'aplicació a la contractació de serveis TIC

Les mesures que caldrà observar en el nou model de contractació de serveis TIC s'estructuren en quatre eixos d'actuació:

image::ict-procurement-p12-cat.svg[Esquema eixos contractació, width=2126, align="center"]

*NOU MODEL DE RELACIÓ*

La visió tradicional de l'acció de l'Administració es basa en l'exercici de l'autoritat d'acord amb la legitimitat que la llei i l'ordenament jurídic li confereixen.
Així, el *procediment administratiu* (i, per tant, també la contractació pública) *s'ha concebut com un procés tancat i extremadament regulat.*
Aquesta concepció ha comportat un model d'Administració que moltes vegades actua de manera intervencionista i autoritària (en el sentit d'actuar amb procediments unilaterals i amb una posició de força)

Pel que fa a la contractació pública, *aquesta unilateralitat ha tingut com a resultat:*

· Adquisició de productes i serveis poc innovadors i allunyats de l'avantguarda del mercat com a resultat de la necessitat de determinar, de manera prèvia a la seva adquisició/adjudicació, tots els requeriments i funcionalitats del servei o producte.

· Procediments llargs i complexos amb una alta càrrega administrativa (i, per tant, uns costs importants per als proveïdors), que han esdevingut una barrera d'accés a la contractació pública per part de les petites empreses.

· Contractes molt detallats i regulats amb una gran rigidesa, que donen molt poc marge a l'adaptació a possibles canvis en les circumstàncies o context durant la seva execució.

*Aquest paradigma, però, està canviant.*
*Les principals línies d'actuació que s'estan impulsant des de l'Ajuntament* per fer efectiu aquest nou marc relacional i contractual són les que s'expliquen a continuació.

*CONSULTES PRELIMINARS*

El marc legal actual contempla la possibilitat d'iniciar un diàleg entre els poders adjudicadors i mercat, previ a l'inici de l'expedient de contractació.
L'objectiu és conèixer i fer prospecció de les solucions que ofereix al mercat per cobrir les necessitats objecte del contracte.

La participació del mercat en la fase de preparació del contracte representa una sèrie d'avantatges en relació amb el model tradicional de contractació. Concretament:

* Permet al mercat *una millor i més profunda comprensió de les necessitats de l'Administració* i possibilita, per tant, que les solucions proposades s'ajustin millor tant en preu com en qualitat al que l'Administració requereix.

* Permet *incorporar les darreres innovacions existents en el mercat*, els darrers estàndards oberts i de programari lliure que poden ser desconeguts per part de l'Administració, especialment en sectors amb gran dinamisme com passa en l'àmbit de les tecnologies i sistemes d'informació.

* És tracta d'un model de contractació amb *més col·laboració entre les parts*, fet que facilita un acostament de l'Administració a la realitat del mercat

*OBERTURA DEL MERCAT*

*Model de relació més obert i transparent amb el sector TIC, amb processos de compra més senzills, eficients i accessibles* per alleugerir la burocràcia i reduir els costos d'accés a la contractació pública.

Per exemple, fer ús de modalitats de licitació com les basades en acords marc, o la subhasta electrònica, que permeten una simplificació del procediment de contractació pública, amb l'objectiu de fer aquesta més accessible i menys costosa per als licitadors.

El procediment de licitació amb negociació també permet un contacte directe entre les empreses i l'òrgan de contractació que és imprescindible, garantint la igualtat de tracte, per definir i adequar les ofertes del mercat i les necessitats municipals.

Els procediments complexos poden esdevenir barreres per a l'accés a la contractació pública de pimes i petits proveïdors, que no disposen dels mitjans necessaris per fer front als requeriments de documentació i procedimentals tradicionals.

És per això que una correcta planificació de les licitacions és important a fi de facilitar a tots els potencials interessats l'elaboració d'ofertes competitives, així com la planificació dels seus recursos, de manera que tinguin temps de fer les inversions necessàries.

L'objectiu de minimitzar aquestes barreres és eixamplar el ventall de proveïdors amb què treballa l'IMI i obrir, així, la compra pública a l'ecosistema d'empreses i professionals locals, amb talent, ajudant a enfortir-lo i fer-lo créixer.

*TRANSPARÈNCIA*

*Facilitar l'accés* per part de proveïdors i ciutadans a informació precisa i actualitzada al voltant dels contractes de l'àmbit de les TIC de l'Ajuntament, *fer més visibles els processos de contractació pública i augmentar-ne la transparència* té efectes molt positius en relació amb l'obertura i accessibilitat d'aquests procediments:

* De cara al ciutadà, que pugui saber com es gasten els seus diners i amb quin criteri, així com els resultats i objectius assolits com a resultat dels contractes ja executats.

* De cara als proveïdors, que puguin accedir en un únic punt a tota la informació associada a la contractació municipal (planificació contractació, criteris i mesures de valoració, posicionament estratègic de l'Ajuntament, etc.) amb la finalitat de fer aquesta més accessible i facilitar la seva planificació de recursos.

*BENEFICIS ESPERATS*

L'objectiu d'aquest nou model de relació és el *foment de procediments de contractació més participatius, accessibles, més àgils i flexibles, amb l'objectiu de:*

* *Reduir els terminis i costos administratius associats als procediments de licitació fent-los més accessibles* a nous proveïdors, especialment les petites i mitjanes empreses d'àmbit local, que són les que conformen el cos central del teixit econòmic.

* *Fer més visibles els processos de contractació pública, i augmentar-ne la transparència,* per fer-los més accessibles i informar el ciutadà de com s'inverteixen els recursos públics, amb quin criteri, així com dels resultats i objectius assolits.

* *Facilitar i afavorir l'adquisició de productes i serveis innovadors, alineats amb els objectius estratègics de l'Ajuntament pel que fa a les TIC* (sobirania tecnològica, ús d'estàndards oberts, etc.) i que incorporin les darreres solucions existents al mercat.

*MODEL DE GESTIÓ DE LES DADES*

*SEGURETAT I ÈTICA DE LES DADES*

El volum de dades generades en l'actualitat ofereix una sèrie d'oportunitats immillorables, però també planteja nous reptes i riscos associats a la seva seguretat.
L'Ajuntament ha de vetllar per la seguretat de les dades del ciutadà i de la ciutat protegint la confidencialitat, la integritat i garantint la qualitat afegint mecanismes adients.

Un dels reptes sorgits d'aquest nou model és l'equilibri entre les polítiques d'obertura i ús de les dades i la privacitat del ciutadà.
La publicació de dades s'ha de fer sempre tenint present que la privacitat del ciutadà es mantindrà inalterada, fins i tot, tenint en compte la superposició de diverses fonts de dades.

El cicle de vida de les dades ha garantir que en totes les seves fases es desenvolupin amb una ètica respectuosa amb el ciutadà.
Des de com es generen les dades, s'emmagatzemen i comparteixen, fins als tractaments i finalitats per a les quals s'utilitzen.

*DADES OBERTES*

L'obertura de dades del sector públic (open public data) és un moviment impulsat per les administracions amb l'objectiu d'aprofitar al màxim els recursos públics disponibles i les actuals capacitats tecnològiques, exposant la informació generada o custodiada per organismes públics i permetent-ne l'accés i la seva reutilització per al benefici de qualsevol persona o entitat interessada.

Aquesta informació pública, de gran valor potencial, pot ser relativa a qualsevol tema i de qualsevol tipus —documents pictogràfics, dades estadístiques, resultats d'estudis o anàlisis, informació sobre els serveis públics, etc.
Empreses, investigadors, altres institucions públiques o la ciutadania en general podran fer ús dels recursos d'informació amb qualsevol finalitat, maximitzant les possibilitats econòmiques i socials que ofereix aquest projecte: foment de la transparència en la gestió, millora dels serveis a la ciutadania, generació d'activitats de negoci i l'impacte social, buscant l'eficiència en la governança.

Per exemple, compartir les dades associades a mobilitat pot facilitar la creació de xarxes de transport públiques més intel·ligents que generin menys congestió, millor mobilitat per a tots els ciutadans i les ciutadanes i costos més baixos d'energia.

En una ciutat democràtica, els ciutadans i les ciutadanes han de poder fer servir i contribuir a un patrimoni comú de coneixements i la participació activa de la ciutadania en la resolució dels reptes de la ciutat.

*BENEFICIS ESPERATS DEL NOU MODEL DE GESTIÓ DE DADES*

L'objectiu d'aquest nou model de gestió de les dades *és posar en valor les dades i la infraestructura d'informació pública de la ciutat i garantir*, com a condició indispensable, *la privacitat i l'ús responsable de les dades* associades als ciutadans i a l'ús dels serveis públics municipals.

Un nou model de gestió de les dades que es generen com a resultat del funcionament de serveis, aplicacions i de l'exercici de les competències municipals.

L'objectiu és disposar d'una infraestructura de dades pública i oberta per desenvolupar aplicacions innovadores data-driven per tenir *un millor accés als serveis públics i una millor qualitat de vida tot garantint, al mateix temps, la sobirania de les dades als ciutadans.*

*NOVA METODOLOGIA DE DESENVOLUPAMENT*

Les noves eines i tecnologies permeten trencar amb el cicle de vida clàssic de construcció de sistemes estructurat en un conjunt de fases molt tancades i d'abast molt concret: definició de requeriments, disseny funcional, disseny tècnic, construcció, proves, proves d'usuari, pas a producció, manteniment.

Aquest trencament es tradueix en una reducció de terminis molt important entre els requeriments i el desplegament (pas a producció).
Les metodologies àgils, en general, aprofiten aquesta reducció per *construir aplicacions d'una manera més eficient, més segura, més atractiva i més focalitzada en les necessitats de l'usuari final.*

*BENEFICIS ESPERATS DE L'ÚS DE METODOLOGIES ÀGILS*

L'ús de metodologies àgils aporta una sèrie d'avantatges en relació amb les metodologies tradicionals, especialment en l'àmbit de la prestació de serveis digitals.
Concretament:

* Posar més el focus en l'usuari final, atès que el fa partícip en tot el procés de disseny, construcció i manteniment de les aplicacions i serveis.

* Ser més flexible i lliurar més valor. Incrementar la flexibilitat en les condicions d'execució, tot afavorint un millor ajust entre requeriments i necessitats reals.

* Facilitar i afavorir l'adquisició de productes i serveis innovadors, que incorporin les darreres solucions existents al mercat.

* Escurçar el temps de desenvolupament. Implementar la millora contínua. Sistematitzar la millora contínua basada en cicles curts d'inspecció i adaptació.

* Transformar la cultura organitzativa. Posant el focus en la col·laboració i transparència.

*SOBIRANIA TECNOLÒGICA*

La dinàmica actual de proveïment de serveis TIC basada, en gran part, en la contractació externa i l'ús de programari propietari ha portat a una certa dependència dels proveïdors TIC per part de l'Ajuntament de Barcelona. Aquesta dependència té certs efectes no desitjats pel que fa al cost de l'adquisició i ús dels sistemes d'informació i de la capacitat de l'Administració per mantenir-lo i evolucionar-lo. Amb l'objectiu de revertir aquesta situació, s'estan endegant una sèrie d'actuacions:

* *Fomentar l'ús prioritari de programari lliure, arquitectura i estàndards oberts* per ajudar a trencar la dependència i el vendor lock-in dels proveïdors, avançant cap a la sobirania tecnològica de l'Ajuntament. Així mateix, es pretén fomentar i intensificar la creació de solucions de manera col·laborativa comptant amb comunitats d'usuaris i altres administracions.

A més, aquesta sobirania tecnològica, promoguda amb estàndards oberts, ha de ser una eina per al bé comú, que generi nova economia, enriqueixi el sector TIC local i faciliti, també, compartir coneixement entre diferents ciutats.

* *Definir nous marcs contractuals que tinguin en compte la capacitació i formació necessàries dels tècnics municipals* implicats en els projectes de disseny i desenvolupament de programari amb la finalitat de minimitzar la dependència envers tercers per a la gestió dels serveis municipals.


*BENEFICIS ESPERATS*

L'objectiu és fer ús preferent del programari lliure, arquitectura i estàndards oberts, així com dotar l'Ajuntament dels perfils i capacitats necessàries per recuperar el coneixement dels serveis TIC vinculats a la gestió de la ciutat i el govern dels serveis digitals.
Amb això es pretén adquirir una sobirania tecnològica que permeti deixar aquest coneixement com a llegat per a la mateixa ciutat.
A més, es deriven altres beneficis com els següents:

* Facilitar la reutilització de sistemes i solucions i millorar l'eficiència de la contractació de productes i serveis informàtics.

* Reduir els costos associats a la prestació i adquisició de serveis i productes TIC a mitjà/llarg termini.

* Garantir la interoperabilitat entre les administracions i entre els diferents serveis digitals de l'Ajuntament.

* No obligar els ciutadans a utilitzar solucions tecnològiques de proveïdors específics.

* Garantir la sobirania tecnològica i la independència de proveïdors específics (evitar el vendor lock-in) i la capacitat d'establir polítiques pròpies i transparents pel que fa a actualitzacions, seguretat i gestió d'incidències.

* Millorar la capacitat d'adaptar i estendre els sistemes digitals de l'Ajuntament a mesura que les necessitats evolucionen i garantir la seva sostenibilitat a llarg termini.


== Aplicabilitat de les mesures en la compra TIC

*Per facilitar l'aplicabilitat de les mesures estratègiques* de l'Ajuntament i de l'IMI que s'han descrit en aquesta mateixa guia *en els futurs contractes vinculats a serveis TIC, es relacionen en l'annex d'aquesta guia una sèrie de “criteris o condicions” que es poden incorporar als plecs* (tècnics i administratius) *en funció de l'abast i objecte del contracte:*

image::ict-procurement-p13-cat.svg[Infografia criteris o condicions, width=2277, align="center"]

La incorporació d'aquests en un procés de vies, que es recullen breument a continuació:

image::ict-procurement-p14-cat.svg[Infografia criteris i condició, width=2361, align="center"]

*Incorporació com a criteri de solvència*

De cara a facilitar la concurrència del màxim nombre de proveïdors en el procés de licitació, els criteris han de ser proporcionats (no excessivament restrictius).

L'objectiu és garantir que les empreses que participin tinguin una solvència econòmica i tècnica que aporti unes garanties suficients pel que fa a la seva capacitat d'executar el contracte.

*Incorporació com a criteri d'adjudicació*

La incorporació com a criteri d'adjudicació permet posar en valor aquelles ofertes o solucions que s'ajustin millor a l'estratègia municipal.
Cal tenir en compte, per tant, que els elements que s'incorporin com a criteri d'adjudicació són de compliment opcional, ja que es tracta d'elements valoratius.

*Incorporació com a condició d'execució*

La incorporació com a condició d'execució implica una obligació per part de l'adjudicatari en l'execució dels treballs objecte del contracte; per tant, la seva inclusió en aquest bloc pretén garantir que els treballs es duen a terme sota les condicions i garanties necessàries d'acord amb l'estratègia municipal pel que fa als serveis TIC.
